pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                sh 'git clone https://github.com/thangacodes/dotnet_webapp.git'
            }
        }
        stage('InfraBuild') {
            steps {
                   sh '''
                      echo "navigating to the Infrabuild_scripts"
                      cd Infrabuild_scripts/
                      terraform init
                      terraform validate
                      terraform plan -var-file terraform.tfvars
                   '''
            }
        }
            stage('DotnetBuild'){
                steps{
                    sh '''
                    cd super-service/
                    tree
                    docker build -t super-service .
                    docker images
                    docker run --name webapp -d -p 8090:80 super-service
                    docker ps 
                    docker ps -a
                    curl -ivk localhost:8090/Time
                    echo "sleep for a while"
                    sleep 30
                    docker stop webapp
                    docker rmi -f $(docker images)
                    yes | docker system prune
                    docker images
                    '''
        }
    }
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }
    }
}
