apiVersion: v1
kind: Service
metadata:
  name: albsvc
spec:
  type: LoadBalancer
  selector:
    app: dotnet
  ports:
    - name: http
      protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-pod
  namespace: project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet 
    spec:
      containers:
        - name: webcont
          image: durai5050/webapp:latest
          imagePullPolicy: Always
